In [30]:
import numpy as np

In [31]:
x=np.array([1,2,3,4,5])
N=5 
matrix = np.column_stack([x**(N-i-1) for i in range(N)])

In [33]:
print(matrix) 

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [36]:
np.linalg.det(matrix)

287.9999999999967

In [34]:
x=np.array([1,2,3,4,5]) 
N=5 
matrix1 = np.vander(x,N,increasing=False)

In [35]:
print(matrix1)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [37]:
np.linalg.det(matrix1)

287.9999999999967